---
development:
  cloud_name: airjoshb
  api_key: ENV.fetch('CLOUDINARY_KEY_ID')
  api_secret: ENV.fetch('CLOUDINARY_ACCESS_KEY')
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: airjoshb
  api_key: ENV.fetch('CLOUDINARY_KEY_ID')
  api_secret: ENV.fetch('CLOUDINARY_ACCESS_KEY')
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: airjoshb
  api_key: ENV.fetch('CLOUDINARY_KEY_ID')
  api_secret: ENV.fetch('CLOUDINARY_ACCESS_KEY')
  enhance_image_tag: true
  static_file_support: false
